layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 12
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
# behance: your_username
# dribbble: your_username
  facebook: rakesh.niraula.9
  hackerrank: rakeshhniraulaa
  instagram: rakesh_niraula
# keybase: your_username
  linkedin: rakesh-niraula-5596b013a
# mastodon: your_username
  medium: /@rakeshhniraulaa
  stackoverflow: users/7456695/walker-at-mind
# telegram: your_username
  twitter: Walker_at_Mind
# unsplash: your_username
# vk: your_username
  website: http://rakeshniraula.com.np
# youtube: your_username

topics:
  - name: Android
    web_url: https://developers.android.com

  - name: Flutter

  - name: Machine Learning

  - name: IOT

  - name: Embedded System

  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Web Development
